### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by lydlovezjr** [easyandroidgroup/EasyAndroid#14]
2020-05-22 18:01:50.243 28381-28797/com.haoge.sample.easyandroid E/AndroidRuntime: FATAL EXCEPTION: EasyLog Printer Thread
    Process: com.haoge.sample.easyandroid, PID: 28381
    java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2523)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2870)
        at com.haoge.easyandroid.easy.EasyFormatter.formatWithArgs(EasyFormatter.kt:45)
        at com.haoge.easyandroid.easy.EasyLog.format(EasyLog.kt:159)
        at com.haoge.easyandroid.easy.EasyLog.access$format(EasyLog.kt:29)
        at com.haoge.easyandroid.easy.EasyLog$e$1.invoke(EasyLog.kt:125)
        at com.haoge.easyandroid.easy.EasyLog$e$1.invoke(EasyLog.kt:29)
        at com.haoge.easyandroid.easy.EasyLog$dispatchToLogPrinterThread$1.run(EasyLog.kt:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by Vicent9920** [comment]
已解决该bug
