### ISSUE TITLE
这个也崩了

### ISSUE THREAD

**Issue by lydlovezjr** [easyandroidgroup/EasyAndroid#15]
2020-05-22 18:04:25.420 29059-29059/com.haoge.sample.easyandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.haoge.sample.easyandroid, PID: 29059
    java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2523)
        at java.util.Formatter.format(Formatter.java:2459)
        at java.lang.String.format(String.java:2870)
        at com.haoge.easyandroid.easy.EasyFormatter.formatWithArgs(EasyFormatter.kt:45)
        at com.haoge.easyandroid.easy.EasyLog.format(EasyLog.kt:159)
        at com.haoge.easyandroid.easy.EasyLog.access$format(EasyLog.kt:29)
        at com.haoge.easyandroid.easy.EasyLog$e$1.invoke(EasyLog.kt:125)
        at com.haoge.easyandroid.easy.EasyLog$e$1.invoke(EasyLog.kt:29)
        at com.haoge.easyandroid.easy.EasyLog.dispatchToLogPrinterThread(EasyLog.kt:149)
        at com.haoge.easyandroid.easy.EasyLog.e(EasyLog.kt:125)
        at com.haoge.easyandroid.easy.EasyLog.e(EasyLog.kt:115)
        at com.haoge.sample.easyandroid.activities.EasySharedPreferencesActivity.createByEasy(EasySharedPreferencesActivity.kt:37)
        at com.haoge.sample.easyandroid.activities.EasySharedPreferencesActivity_ViewBinding$2.doClick(EasySharedPreferencesActivity_ViewBinding.java:43)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7138)
        at android.view.View.access$3500(View.java:811)
        at android.view.View$PerformClick.run(View.java:27419)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Vicent9920** [comment]
已解决
