### ISSUE TITLE
这个也崩了

### ISSUE THREAD

**Issue by lydlovezjr** [easyandroidgroup/EasyAndroid#16]
2020-05-22 18:08:00.004 1613-3786/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2020-05-22 18:08:00.821 6712-6860/? E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: MIME type image/jpeg cannot be inserted into content://media/external/audio/media; expected MIME type under audio/*
        at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:2141)
        at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:2008)
        at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:2576)
        at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:3175)
        at com.android.providers.media.MediaProvider.insert(MediaProvider.java:2988)
        at android.content.ContentProvider$Transport.insert(ContentProvider.java:309)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:154)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2020-05-22 18:08:00.826 1328-1328/com.haoge.sample.easyandroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.haoge.sample.easyandroid, PID: 1328
    java.lang.IllegalArgumentException: MIME type image/jpeg cannot be inserted into content://media/external/audio/media; expected MIME type under audio/*
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
        at android.content.ContentResolver.insert(ContentResolver.java:1844)
        at com.haoge.easyandroid.easy.EasyMedia.getAudio(EasyMedia.kt:372)
        at com.haoge.sample.easyandroid.activities.EasyPhotoActivity.getAudio(EasyPhotoActivity.kt:98)
        at com.haoge.sample.easyandroid.activities.EasyPhotoActivity_ViewBinding$9.doClick(EasyPhotoActivity_ViewBinding.java:120)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:7161)
        at android.view.View.performClickInternal(View.java:7138)
        at android.view.View.access$3500(View.java:811)
        at android.view.View$PerformClick.run(View.java:27419)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Vicent9920** [comment]
已解决

**Comment by Kucingemas** [comment]
你好，这个怎么解决？
